idf_component_register(SRCS 
"control/quadcopter_control.c"
"comminication/esp_now_comm.c"
"comminication/web_comm.c"
"command_line_interface.c"
"storage/nv_storage.c"
"comminication/uart.c"
"sensors/icm42688p.c"
"dshot_esc_encoder.c"
"comminication/i2c.c"
"comminication/spi.c"
"sensors/qmc5883l.c"
"sensors/hmc5883l.c"
"storage/blackbox.c"
"sensors/tf_luna.c"
"sensors/pmw3901.c"
"sensors/bmp390.c"
"sensors/ublox.c"
"calibration.c"
"quaternion.c"
"defaults.c"
"filters.c"
"gpio.c" 
"main.c"
"ibus.c"
"sbus.c"
"hitl.c"
"parameters/mc_controller_params.c"
"parameters/general_params.c"
"parameters/filter_params.c"
"parameters/estimator_params.c"
"parameters/param.c"
"../components/ecl/airdata/WindEstimator.cpp"
"../components/ecl/EKF/airspeed_fusion.cpp"
"../components/ecl/EKF/control.cpp"
"../components/ecl/EKF/covariance.cpp"
"../components/ecl/EKF/drag_fusion.cpp"
"../components/ecl/EKF/ekf_helper.cpp"
"../components/ecl/EKF/ekf.cpp"
"../components/ecl/EKF/EKFGSF_yaw.cpp"
"../components/ecl/EKF/estimator_interface.cpp"
"../components/ecl/EKF/gps_checks.cpp"
"../components/ecl/EKF/gps_yaw_fusion.cpp"
"../components/ecl/EKF/imu_down_sampler.cpp"
"../components/ecl/EKF/mag_control.cpp"
"../components/ecl/EKF/mag_fusion.cpp"
"../components/ecl/EKF/optflow_fusion.cpp"
"../components/ecl/EKF/sensor_range_finder.cpp"
"../components/ecl/EKF/sideslip_fusion.cpp"
"../components/ecl/EKF/terrain_estimator.cpp"
"../components/ecl/EKF/utils.cpp"
"../components/ecl/EKF/vel_pos_fusion.cpp"
"../components/ecl/geo/geo.cpp"
"../components/ecl/geo_lookup/geo_mag_declination.cpp"
"../components/ecl/ecl_c_wrapper.cpp"


INCLUDE_DIRS ".")

target_compile_options(${COMPONENT_LIB} PRIVATE 
    -Wno-unused-variable
    -Wno-unused-function
)